### ISSUE TITLE
No such file or directory: '/home/jianming_ge/workplace/firefront-master/py3_tools/../examples/aullene/0-2009-07-24T14-57-39Z.ffgeojson'

### ISSUE THREAD

**Issue by justinge** [forefireAPI/firefront#23]
(base) [jianming_ge@localhost py3_tools]$ python coord_to_ff.py
sh: forefire: 未找到命令
Traceback (most recent call last):
  File "/home/jianming_ge/workplace/firefront-master/py3_tools/coord_to_ff.py", line 38, in <module>
    main()
  File "/home/jianming_ge/workplace/firefront-master/py3_tools/coord_to_ff.py", line 34, in main
    ff.convert_to_geojson(output_path + '0-2009-07-24T14-57-39Z.ffgeojson')
  File "/home/jianming_ge/workplace/firefront-master/py3_tools/forefirepy/ForeFire.py", line 74, in convert_to_geojson
    ffjson2geojson(path)
  File "/home/jianming_ge/workplace/firefront-master/py3_tools/forefirepy/ff2geojson.py", line 17, in ffjson2geojson
    ff_geojson = load_json(filepath)
  File "/home/jianming_ge/workplace/firefront-master/py3_tools/forefirepy/ff2geojson.py", line 6, in load_json
    with open(file_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/jianming_ge/workplace/firefront-master/py3_tools/../examples/aullene/0-2009-07-24T14-57-39Z.ffgeojson'

**Comment by ludobegins** [comment]
It looks like there was a problem generating the `ffgeosjon` file, so maybe there was an issue with the simulation itself. Is the forefire executable properly installed? You can refer to the [wiki](https://github.com/forefireAPI/firefront/wiki)

**Comment by antonio-leblanc** [comment]
This issue was closed because it has been inactive for 90 days. If you still need help it can be re-opened
